### ISSUE TITLE
Fody/AutoDI: System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by SlowLogicBoy** [Keboo/AutoDI#104]
CSProj: (Library project)
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoDI.Fody" Version="3.1.0"/>
    <PackageReference Include="PropertyChanged.Fody" Version="2.2.9"/>
  </ItemGroup>
</Project>
```

Same error happens when using 3.2.0-ci68

FodyWeavers.xml:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <AutoDI/>
  <PropertyChanged/>
</Weavers>
```

Build exception I get:
```
>dotnet run
MSBUILD : warning : Fody/AutoDI: Failed to find AutoDI assembly. Manually injecting 'C:\Users\user\.nuget\packages\autodi\3.1.0\lib\netstandard1.0\AutoDI.dll' [D:\Code\Git\dnScripts\Projects\Clients\Mako.Desktop\Mako.Desktop.csproj]
MSBUILD : error : Fody/AutoDI: System.NotImplementedException: The method or operation is not implemented. [D:\Code\Git\dnScripts\Projects\Clients\Mako.Desktop\Mako.Desktop.csproj]
MSBUILD : error :    at Mono.Cecil.DefaultReflectionImporter.ResolveMethodDefinition(MethodBase method) [D:\Code\Git\dnScripts\Projects\Clients\Mako.Desktop\Mako.Desktop.csproj]
MSBUILD : error :    at Mono.Cecil.DefaultReflectionImporter.ImportMethod(MethodBase method, ImportGenericContext context, ImportGenericKind import_kind) [D:\Code\Git\dnScripts\Projects\Clients\Mako.Desktop\Mako.Desktop.csproj]
MSBUILD : error :    at Mono.Cecil.DefaultReflectionImporter.ImportReference(MethodBase method, IGenericParameterProvider context) [D:\Code\Git\dnScripts\Projects\Clients\Mako.Desktop\Mako.Desktop.csproj]
MSBUILD : error :    at ModuleWeaver.GenerateInitMethod(MethodDefinition configureMethod, FieldDefinition globalServiceProvider) [D:\Code\Git\dnScripts\Projects\Clients\Mako.Desktop\Mako.Desktop.csproj]
MSBUILD : error :    at ModuleWeaver.GenerateAutoDIClass(Mapping mapping, Settings settings, MethodDefinition& initMethod) [D:\Code\Git\dnScripts\Projects\Clients\Mako.Desktop\Mako.Desktop.csproj]
MSBUILD : error :    at ModuleWeaver.Execute() [D:\Code\Git\dnScripts\Projects\Clients\Mako.Desktop\Mako.Desktop.csproj]
MSBUILD : error :  [D:\Code\Git\dnScripts\Projects\Clients\Mako.Desktop\Mako.Desktop.csproj]

The build failed. Please fix the build errors and run again.
```

**Comment by Keboo** [comment]
Looks like the issue is likely coming from running with teh `dotnet` cli. I will see what it takes to fix it.

**Comment by Keboo** [comment]
@SlowLogicBoy just published AutoDI.3.2.0-ci70, it should fix the issue.

**Comment by SlowLogicBoy** [comment]
@Keboo thanks for fast resposne.

Still having the same issue :/
updated:
`<PackageReference Include="AutoDI.Fody" Version="3.2.0-ci70"/>`

tried removing `obj` `bin` directories, 
`dotnet clean`
`dotnet build`.

**Comment by Keboo** [comment]
Hm.... interesting. I am seeing the same, but only on the first build. Appears to succeed on subsequent builds.

**Comment by SlowLogicBoy** [comment]
YEa but if I run that build:
```
Unhandled Exception: AutoDI.NotInitializedException: AutoDI has not been initialized
   at AutoDI.GlobalDI.GetService[T](Object[] parameters)
```

**Comment by Keboo** [comment]
Putting this here for my own reference.
[This](https://github.com/jbevain/cecil/blob/master/Mono.Cecil/Import.cs#L377) is the exception case we are hitting. It is caused by trying to [import a method from a generic class](https://github.com/jbevain/cecil/blob/master/Mono.Cecil/Import.cs#L390-L391). There are several instances of this in the  `GenerateInitMethod`. Need to figure out proper way to handle this in net core.

**Comment by SlowLogicBoy** [comment]
I guess for now I will be manually doing DI stuff, and keep an eye on this project ;). Thanks.

**Comment by Keboo** [comment]
More progress. Need to investigate work arounds for core builds until Cecil moves to netstandard2.0 and it gets integrated with Fody. https://github.com/jbevain/cecil/issues/505

Re-opening so I don't lose track of this.

**Comment by Keboo** [comment]
@SlowLogicBoy can you test the latest preview nuget 3.2.0-ci79 and let me know if it resolves this issue.

**Comment by SlowLogicBoy** [comment]
Works perfectly now!

Thanks for the fix.

**Comment by Keboo** [comment]
Great! The fix was actually down down in the Mono.Cecil/Fody libs, I just got all of the changes pulled in and things are getting a bit cleaner. I am hoping to get my 3.2.0 release done sometime in the next couple weeks so there should be an official update soon.
